### ISSUE TITLE
error: package io.flutter.plugin.common.PluginRegistry does not exist

### ISSUE THREAD

**Issue by Rechunk** [rxlabz/audioplayer#1]
This is the issue I get when I try to run my flutter app. I haven't written any code using the plugin yet, I am still setting it up.

**Comment by rxlabz** [comment]
did you install the plugin from pub.lang ?

**Comment by Rechunk** [comment]
All I did was clone the repo into my project and added the dependency

**Comment by rxlabz** [comment]
Did you update with the version I published today ?
anyway, can you please try to install it, as a Flutter plugin from pub.dartlang, as described in the readme.

**Comment by Rechunk** [comment]
Yes, I upgraded Flutter and installed it from pub.dartlang, works fine now. Thank you :)

**Comment by rxlabz** [comment]
🎉
