### ISSUE TITLE
Stupid question, but where is the audio file in the example stored?

### ISSUE THREAD

**Issue by anchpop** [rxlabz/audioplayer#11]
It's playing this weird audio about dog vivisection in the uk, not sure where it's getting it from! Sorry, I know this is dumb, thank you for any help you can give!

**Comment by rxlabz** [comment]
@anchpop I'm not sure to understand the question, but the sound is played from a server https://github.com/rxlabz/audioplayer/blob/3deb3b693f985b049356205ec72e81e060ffea83/example/lib/main.dart#L12

**Comment by anchpop** [comment]
@rxlabz thank you much! I'm not sure how I missed that
