### ISSUE TITLE
Is this package dead? Alternatives?

### ISSUE THREAD

**Issue by nstrelow** [rxlabz/audioplayer#116]
@rxlabz Is this repository still maintained?

It seems like there are a lot of open issues and pull requests without any replies.

Just shoot us an update so people know if they need to move on to a different package.

**Comment by rxlabz** [comment]
Hi, the package is back to life! Today version 0.6.0 with MacOS support & 0.7.0 with web support were released. I'll review the other PRs in the coming weeks.

**Comment by nstrelow** [comment]
WHUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

Well then I take back everything :D

Thanks for finding the time @rxlabz !
