### ISSUE TITLE
IOS connection lost

### ISSUE THREAD

**Issue by Solido** [rxlabz/audioplayer#15]
First I've downloaded the file then click on Play Local 

`*** First throw call stack:
(
	0   CoreFoundation                      0x000000010409212b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001046a9f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104113024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000104014f78 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000104014958 _CF_forwarding_prep_0 + 120
	5   audioplayer                         0x000000010394e04a -[AudioplayerPlugin togglePlay:isLocal:] + 170
	6   audioplayer                         0x000000010394da93 __45-[AudioplayerPlugin handleMethodCall:result:]_block_invoke + 563
	7   audioplayer                         0x000000010394d691 -[AudioplayerPlugin handleMethodCall:result:] + 1169
	8   Flutte<…>
Lost connection to device.`

I like this plugin I want to make an app around it !

**Comment by Solido** [comment]
Changed the MP3 file from your example to mine and it worked ?!

**Comment by Kretin1** [comment]
I'm having this problem with one file, but not another.

Did you figure out what was different about your mp3 file?

**Comment by Solido** [comment]
No idea !

**Comment by Kretin1** [comment]
Thanks. Turns out the file is fine, just having trouble playing consecutive audio files. Playing the same file over and over is fine. Playing a second file causes the crash.
