### ISSUE TITLE
AudioPlayer blocks UI on Andorid

### ISSUE THREAD

**Issue by the4thfloor** [rxlabz/audioplayer#20]
The call to prepare() can take a long time to execute, because it might involve fetching and decoding media data. So, as is the case with any method that may take long to execute, you should never call it from your application's UI thread.

https://developer.android.com/guide/topics/media/mediaplayer.html#preparingasync

**Comment by Rmaan** [comment]
From my observations, it could block UI more than a second specially in case of poor network. I may send a pull request if I had time to fix it.

**Comment by rxlabz** [comment]
Hi, sorry for the delay, and thanks for the suggestion, thanks to @mindon https://github.com/rxlabz/audioplayer/pull/18, it's updated !
