### ISSUE TITLE
Pause stops instead of pause

### ISSUE THREAD

**Issue by arkaray** [rxlabz/audioplayer#29]
I copied, pasted (and modified the names a bit) this code from [here](https://pub.dartlang.org/packages/audioplayer):

    void _pause() async {
      final result = await player.pause();
      if (result == 1) setState(() => playerState = PlayerState.paused);
    }

but player starts from the start when following is invoked:

    void _play() async {
      final result = await player.play(kUrl);
      if (result == 1) setState(() => playerState = PlayerState.playing);
    }
I am using Android 7.1.1 on Moto G5S to test.

Console message on pause:
`W/MediaPlayer(24746): mediaplayer went away with unhandled events`

**Comment by rxlabz** [comment]
hi, does the pause button works for you in the example app ?

**Comment by arkaray** [comment]
yes, seems like something else is causing the problem(extremely sorry)
