### ISSUE TITLE
Playing from assets

### ISSUE THREAD

**Issue by mrbech** [rxlabz/audioplayer#5]
I can't seem to figure out how to play a file from flutter assets, is it possible?

**Comment by rxlabz** [comment]
I did not tried... I don't know if it is possible to find assets path ?
Else maybe you can read bytes from assets, then write the asset content to a local file, and then play from local file system ?

**Comment by mrbech** [comment]
It might be possible to find the assets path somewhere in the flutter source, but that might change over time, hopefully flutter will expose this path in the future. I went with your suggestion, reading from assets and writing to local file, works for now :) Thanks for the suggestion. For anyone who needs it, here is a code snippet that can transfer the file on app boot if its not there yet:

```
final dir = await getApplicationDocumentsDirectory();
final file = new File("${dir.path}/<local file name>.mp3");
if(!(await file.exists())) {
    final soundData = await rootBundle.load("<file in assets>.mp3");
    final bytes = soundData.buffer.asUint8List();
    await file.writeAsBytes(bytes, flush: true);
}
```

**Comment by Jawnnypoo** [comment]
Just for completion, here is a class I made that takes @mrbech 's example code and rounds it out:

```dart
import 'dart:async';
import 'dart:io';

import 'package:audioplayer/audioplayer.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter/services.dart' show rootBundle;

class SoundManager {
  AudioPlayer audioPlayer = new AudioPlayer();

  Future playLocal(localFileName) async {
    final dir = await getApplicationDocumentsDirectory();
    final file = new File("${dir.path}/$localFileName");
    if (!(await file.exists())) {
      final soundData = await rootBundle.load("assets/$localFileName");
      final bytes = soundData.buffer.asUint8List();
      await file.writeAsBytes(bytes, flush: true);
    }
    await audioPlayer.play(file.path, isLocal: true);
  }
}
```

Then, you would call it like:

```dart
SoundManager soundManager = new SoundManager();

  void _playSound() {
    soundManager.playLocal("name_of_your_file.mp3").then((onValue) {
      //do something?
    });
  }
```
Note that this requires adding `path_provider:` to your `pubspec.yml` and don't forget to register your assets in your pubspec as well

**Comment by EidarousDev** [comment]
> Just for completion, here is a class I made that takes @mrbech 's example code and rounds it out:
> 
> ```dart
> import 'dart:async';
> import 'dart:io';
> 
> import 'package:audioplayer/audioplayer.dart';
> import 'package:path_provider/path_provider.dart';
> import 'package:flutter/services.dart' show rootBundle;
> 
> class SoundManager {
>   AudioPlayer audioPlayer = new AudioPlayer();
> 
>   Future playLocal(localFileName) async {
>     final dir = await getApplicationDocumentsDirectory();
>     final file = new File("${dir.path}/$localFileName");
>     if (!(await file.exists())) {
>       final soundData = await rootBundle.load("assets/$localFileName");
>       final bytes = soundData.buffer.asUint8List();
>       await file.writeAsBytes(bytes, flush: true);
>     }
>     await audioPlayer.play(file.path, isLocal: true);
>   }
> }
> ```
> 
> Then, you would call it like:
> 
> ```dart
> SoundManager soundManager = new SoundManager();
> 
>   void _playSound() {
>     soundManager.playLocal("name_of_your_file.mp3").then((onValue) {
>       //do something?
>     });
>   }
> ```
> 
> Note that this requires adding `path_provider:` to your `pubspec.yml` and don't forget to register your assets in your pubspec as well

÷ I found this as the best alternative solution for asset_audio_player deprecated package. Thanks a LOT!!

**Comment by sprakash** [comment]
this is helpful, however what if I want to write audio data in a json file ... I want information like : 
sampleRate
sampleSize
bits 
lenght 

all this to be stored in json format ... would I even get this from mp3 ? or wav format ? Is this feasible ? Also this isn't a stored audio file, I want this data from a recorded sound that I record using audio_player package

**Comment by WastedHymn** [comment]
> Just for completion, here is a class I made that takes @mrbech 's example code and rounds it out:
> 
> ```dart
> import 'dart:async';
> import 'dart:io';
> 
> import 'package:audioplayer/audioplayer.dart';
> import 'package:path_provider/path_provider.dart';
> import 'package:flutter/services.dart' show rootBundle;
> 
> class SoundManager {
>   AudioPlayer audioPlayer = new AudioPlayer();
> 
>   Future playLocal(localFileName) async {
>     final dir = await getApplicationDocumentsDirectory();
>     final file = new File("${dir.path}/$localFileName");
>     if (!(await file.exists())) {
>       final soundData = await rootBundle.load("assets/$localFileName");
>       final bytes = soundData.buffer.asUint8List();
>       await file.writeAsBytes(bytes, flush: true);
>     }
>     await audioPlayer.play(file.path, isLocal: true);
>   }
> }
> ```
> 
> Then, you would call it like:
> 
> ```dart
> SoundManager soundManager = new SoundManager();
> 
>   void _playSound() {
>     soundManager.playLocal("name_of_your_file.mp3").then((onValue) {
>       //do something?
>     });
>   }
> ```
> 
> Note that this requires adding `path_provider:` to your `pubspec.yml` and don't forget to register your assets in your pubspec as well

I've been trying to make [audiotagger's](https://pub.dev/packages/audiotagger) "readTagsAsMap" method work  for hours. I was using directly "assets/mp3/Doomsday.mp3" as a path. It was always saying "java.io.FileNotFoundException: Unable to find:assets/mp3/Doomsday.mp3". After using your code it worked!

```dart
final dir = await getApplicationDocumentsDirectory();
     final file = new File("${dir.path}/$localFileName");
     if (!(await file.exists())) {
       final soundData = await rootBundle.load("assets/$localFileName");
       final bytes = soundData.buffer.asUint8List();
       await file.writeAsBytes(bytes, flush: true);
     }
```
Thank you!
