### ISSUE TITLE
Failed assertion: line 81 pos 16: '_state == AudioPlayerState.PLAYING': is not true

### ISSUE THREAD

**Issue by DevilWarrior** [rxlabz/audioplayer#52]
Hi,

I'm building a messaging app and I'm getting the error on the title line when playing a local file. I'm calling the audioPlayer.play() withing the message element. Since there are a lot of them I'm building the AudioPlayer object when tapping on an audio message and than trying to dispose it afterwards. In doing so the audio does play but the app crashes right afterwards with the error mentioned above. Any help is greatly appreciated.

```
# Here I initialized the AudioPlayer
audioPlayer = new AudioPlayer();

# Here I play the audio file, it crashes here 
await audioPlayer.play(_audioPath, isLocal: true);
setState(() => playerState = PlayerState.playing);
```

**Comment by eddywm** [comment]
Hi, 
I'm not sure you need to await and also you don't absolutely have to specify whether the file is local or not.

Maybe you should look at the code samples again and the example project.

**Comment by DevilWarrior** [comment]
The example does use await. And there's a method for _playLocal hence why I used it.

```
  Future play() async {
    await audioPlayer.play(kUrl);
    setState(() {
      playerState = PlayerState.playing;
    });
  }

  Future _playLocal() async {
    await audioPlayer.play(localFilePath, isLocal: true);
    setState(() => playerState = PlayerState.playing);
  }
```

**Comment by ThinkDigitalSoftware** [comment]
This is still an issue. what does it indicate, @DevilWarrior?

**Comment by DevilWarrior** [comment]
I believe the issue got solved but I can't quite remember now how. Will close this unless you think otherwise.

**Comment by ThinkDigitalSoftware** [comment]
It's still an issue for me. I can't diagnose it because everything in our code seems to be just fine

**Comment by DevilWarrior** [comment]
Sorry, I just realized your previous comment was sent a separate user, re-opening in case someone else want to comment on this.
