### ISSUE TITLE
Support of Obj-C version?

### ISSUE THREAD

**Issue by EasonPai** [rxlabz/audioplayer#6]
I am trying to test audioplayer plugin with the [FriendlyChat](https://github.com/flutter/friendlychat-steps/tree/master/full_steps/step_6_image_support)  source.

When I do "edit/convert/To Current Swift Syntax" and I selected all items in this screen
![](https://drive.google.com/uc?export=view&id=0B--vmbY9Aph1ZmhFdVlZNjd1RjQ )

and I get this message
![](https://drive.google.com/uc?export=view&id=0B--vmbY9Aph1b2lqUlJKMTRXMG8)

then I add plugins to yaml and run, I get error

> Launching lib/main.dart on iPhone SE in debug mode...
> 
> Running pod install...
> 
> Error running pod install: Exit code 1 from: pod install
> 
> Error launching application on iPhone SE.

**Comment by rxlabz** [comment]
I just tried, and it works after when I add *use frameworks!* to the podfile as in https://github.com/rxlabz/audioplayer/blob/master/example/ios/Podfile

**Comment by EasonPai** [comment]
I still got the same error after I removed comment on `use_frameworks!`, that's strange...

But isn't official flutter team [suggested](https://github.com/flutter/flutter/issues/9694) to comment out `use_frameworks!` when using **google sign in** and **firebase**?

**Comment by rxlabz** [comment]
sorry I never used google signin... but I will in the next days or weeks, and will add some info if I find some :(

**Comment by rxlabz** [comment]
thanks to @johanhenselmans I can close this one !
