### ISSUE TITLE
Audio player unresponsive after stopping and creating new instance in a new isolate

### ISSUE THREAD

**Issue by hacker1024** [rxlabz/audioplayer#70]
I can't really explain this well in the short title.
I'm using the [ryanheise/audio_service](https://github.com/ryanheise/audio_service/) plugin.
This plugin launches an isolate for background dart  code execution upon starting the audio service. In this isolate code (which I'll refer to as an "audio task") I implement callbacks and start, pause play, etc. an `AudioPlayer` instance. If, however, I stop the audio task, and start a new one (creating a new `AudioPlayer` instance in a new isolate), I can _start_ playback okay, but nothing else works. I can't play, pause or stop the player. The futures for the `AudioPlayer` methods do finish, though. The method calls don't broadcast anything in the `onPlayerStateChanged` stream, either.

If you need my code to debug, I'd happily put up a private repo.

**Comment by shubham-cueclad** [comment]
You don't need to use isolate i have done it without isolate by just keeping object of AudioPlayer static and accessing it through all the app.and then getting all the required methods.

**Comment by hacker1024** [comment]
Static objects do not persist between isolates. I need to use an isolate for background code execution.

**Comment by manojdvs123** [comment]
how to play another audio , im trying to change the audio no button click . but it is giving me errors.

**Comment by hacker1024** [comment]
I'm not sure what was causing this issue - it could have either been this plugin or my own code. Regardless, it's not happening anymore, and as no-one seems to be getting this issue, I'll close this down.

@manojdvs123, it completely depends on your own code. Furthermore, those errors _do_ exist for a reason - how do you expect anyone to help you if you don't even provide the most basic debugging information? This isn't the place to discuss such things anyway.
