### ISSUE TITLE
 not working with url more than thirty minutes

### ISSUE THREAD

**Issue by quocson1** [rxlabz/audioplayer#80]
URL AUDIO : http://files.vixahoi.com/SachDangHoanThien/VietNamPhongTuc/02.P01B_NoiVePhongTucTrongGiaToc_VietNamPhongTuc.mp3
<img width="1081" alt="Screen Shot 2019-03-29 at 8 05 54 PM" src="https://user-images.githubusercontent.com/29052846/55234616-1ee15c80-525e-11e9-99fe-65c23cd826a0.png">

**Comment by kaifiappsmaven** [comment]
I am facing same issue. Can you tell how did you solve this?
